# Generated by Django 4.1.2 on 2022-11-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
