# Generated by Django 4.1.2 on 2022-10-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_date_created_on_product_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='date',
        ),
    ]
