# Generated by Django 4.1.2 on 2022-11-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_rating_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='view_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
